groups:
  - name: example
    rules:
      - alert: HighRequestLatency
        expr: http_request_duration_seconds{quantile="0.9"} > 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High request latency on {{ $labels.instance }}"